CREATE TABLE `BAOFU_CRM`.`T_DECISION_FLOW` (
  `DECISION_FLOW_ID` VARCHAR(100) NOT NULL COMMENT '决策流 ID',
  `DECISION_NAME` VARCHAR(200) NOT NULL COMMENT '决策流名称',
  `DESCRIPTION` VARCHAR(500) NULL COMMENT '决策流描述',
  `STATUS` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`DECISION_FLOW_ID`),
  INDEX `IDX_STATUS` (`STATUS`),
  INDEX `IDX_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='决策流主表';