CREATE TABLE `PAYFUL_BRMS`.`T_PARAM_RELATION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SCENE` VARCHAR(100) NOT NULL COMMENT '场景类型',
  `CODE` VARCHAR(100) NOT NULL COMMENT '参数编码',
  `BIZ_ID` VARCHAR(100) NOT NULL COMMENT '业务 ID',
  `TARGET_SOURCE` VARCHAR(100) NOT NULL COMMENT '目标来源',
  `STATUS` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT '状态',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `IDX_SCENE_CODE` (`SCENE`, `CODE`),
  INDEX `IDX_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='参数关联表';