# -*- coding: utf-8 -*-
# ---
# @Author: duansea
# @Time: 2023-11-23 10:44
# ---
"""使用 selenium IDE录制的脚本"""
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSerch():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testSerch(self):
        self.driver.get("https://home-test.scrm.keyid.cn/home")
        self.driver.set_window_size(1244, 672)
        self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary > span").click()
        time.sleep(10)
        self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__close path").click()


if __name__ == '__main__':
    pytest.main('-vs')