# Generated by Django 4.1.4 on 2024-01-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='ids',
            new_name='id',
        ),
    ]
