# Generated by Django 4.1.4 on 2024-01-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappsea', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.AddField(
            model_name='projects',
            name='ids',
            field=models.IntegerField(default=1, help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
            preserve_default=False,
        ),
    ]
