# Generated by Django 4.1.4 on 2024-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappsea', '0003_alter_projects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='is_excue',
            field=models.BooleanField(default=True, help_text='是否启动项目', verbose_name='是否启动项目'),
        ),
    ]
