# Generated by Django 4.1.4 on 2022-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
                ('spwd', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'mydjango',
            },
        ),
    ]
